import Profiel from "../../assets/docasnaLoga/profile.jpeg";

export const playedMatchData = {
  idZapasu: "1",
  date: "02 Feb, 2024",
  homeTeam: "Melvik",
  awayTeam: "Tubor",
  homeScore: 32,
  awayScore: 25,
  homeLogo: "/path-to-home-logo.png",
  homeMatch: true,
};

export const playerData = [
  {
    idPlayer: "1",
    name: "Richard N.",
    position: "LB",
    goals: 32,
    playedMatches: 24,
    shots: 40,
    dresNumber: 11,
    accuracy: 80,
    profileImg: Profiel,
    sixMetersGoals: 10,
    sixMetersShots: 15,
    sevenMetersGoals: 5,
    sevenMetersShots: 7,
    nineMetersGoals: 3,
    nineMetersShots: 5,
    wingGoals: 12,
    wingShots: 16,
    breakGoals: 2,
    breakShots: 3,
    differenceOffence: -15,
    differenceDefence: 3,
    yellowCards: 1,
    twoMinutes: 2,
    redCards: 0,
    assists: 10,
  },
  {
    idPlayer: "2",
    name: "Jane D.",
    position: "FW",
    goals: 28,
    playedMatches: 11,
    shots: 35,
    dresNumber: 31,
    accuracy: 78,
    profileImg: "Profiel",
    sixMetersGoals: 8,
    sixMetersShots: 10,
    sevenMetersGoals: 4,
    sevenMetersShots: 6,
    nineMetersGoals: 6,
    nineMetersShots: 9,
    wingGoals: 10,
    wingShots: 12,
    breakGoals: 1,
    breakShots: 2,
    differenceOffence: 12,
    differenceDefence: 20,
    yellowCards: 0,
    twoMinutes: 1,
    redCards: 0,
    assists: 8,
  },
  {
    idPlayer: "3",
    name: "Jane D.",
    position: "FW",
    goals: 28,
    playedMatches: 11,
    shots: 35,
    dresNumber: 31,
    accuracy: 78,
    profileImg: "Profiel",
    sixMetersGoals: 8,
    sixMetersShots: 10,
    sevenMetersGoals: 4,
    sevenMetersShots: 6,
    nineMetersGoals: 6,
    nineMetersShots: 9,
    wingGoals: 10,
    wingShots: 12,
    breakGoals: 1,
    breakShots: 2,
    differenceOffence: 12,
    differenceDefence: 20,
    yellowCards: 0,
    twoMinutes: 1,
    redCards: 0,
    assists: 8,
  },
  {
    idPlayer: "4",
    name: "Jane D.",
    position: "FW",
    goals: 28,
    playedMatches: 11,
    shots: 35,
    dresNumber: 31,
    accuracy: 78,
    profileImg: "Profiel",
    sixMetersGoals: 8,
    sixMetersShots: 10,
    sevenMetersGoals: 4,
    sevenMetersShots: 6,
    nineMetersGoals: 6,
    nineMetersShots: 9,
    wingGoals: 10,
    wingShots: 12,
    breakGoals: 1,
    breakShots: 2,
    differenceOffence: 12,
    differenceDefence: 20,
    yellowCards: 0,
    twoMinutes: 1,
    redCards: 0,
    assists: 8,
  },
  {
    idPlayer: "5",
    name: "Jane D.",
    position: "FW",
    goals: 28,
    playedMatches: 11,
    shots: 35,
    dresNumber: 31,
    accuracy: 78,
    profileImg: "Profiel",
    sixMetersGoals: 8,
    sixMetersShots: 10,
    sevenMetersGoals: 4,
    sevenMetersShots: 6,
    nineMetersGoals: 6,
    nineMetersShots: 9,
    wingGoals: 10,
    wingShots: 12,
    breakGoals: 1,
    breakShots: 2,
    differenceOffence: 12,
    differenceDefence: 20,
    yellowCards: 0,
    twoMinutes: 1,
    redCards: 0,
    assists: 8,
  },
  {
    idPlayer: "6",
    name: "Jane D.",
    position: "FW",
    goals: 28,
    playedMatches: 11,
    shots: 35,
    dresNumber: 31,
    accuracy: 78,
    profileImg: "Profiel",
    sixMetersGoals: 8,
    sixMetersShots: 10,
    sevenMetersGoals: 4,
    sevenMetersShots: 6,
    nineMetersGoals: 6,
    nineMetersShots: 9,
    wingGoals: 10,
    wingShots: 12,
    breakGoals: 1,
    breakShots: 2,
    differenceOffence: 12,
    differenceDefence: 20,
    yellowCards: 0,
    twoMinutes: 1,
    redCards: 0,
    assists: 8,
  },
  {
    idPlayer: "7",
    name: "Jane D.",

    position: "FW",
    goals: 28,
    playedMatches: 11,
    shots: 35,
    dresNumber: 31,
    accuracy: 78,
    profileImg: "Profiel",
    sixMetersGoals: 8,
    sixMetersShots: 10,
    sevenMetersGoals: 4,
    sevenMetersShots: 6,
    nineMetersGoals: 6,
    nineMetersShots: 9,
    wingGoals: 10,
    wingShots: 12,
    breakGoals: 1,
    breakShots: 2,
    differenceOffence: 12,
    differenceDefence: 20,
    yellowCards: 0,
    twoMinutes: 1,
    redCards: 0,
    assists: 8,
  },
];

export const matches = [
  {
    idZapasu: "1",
    date: "02 Feb, 2024",
    homeTeam: "Melvik",
    awayTeam: "Tubor",
    homeScore: 32,
    awayScore: 25,
    homeLogo: "/path-to-home-logo.png",
    homeMatch: true,
  },
  {
    idZapasu: "2",
    date: "10 Jan, 2024",
    homeTeam: "Arsenal",
    awayTeam: "West Ham",
    homeScore: 28,
    awayScore: 22,
    homeLogo: "/path-to-arsenal-logo.png",
    homeMatch: false,
  },
  {
    idZapasu: "3",
    date: "15 Jan, 2024",
    homeTeam: "Chelsea",
    awayTeam: "Liverpool",
    homeScore: 18,
    awayScore: 21,
    homeLogo: "/path-to-chelsea-logo.png",
    homeMatch: true,
  },
];
